### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by noskill**
use callback to update cache in RobustObserver and world_state in MConnector when a new observation is received

### CODE REVIEW

**Review by Necr0x0Der — APPROVED** [review]
Works for me.

**Comment by noskill** [comment]
Indeed, on my machine test_observation_from_triples fails sometimes

**Comment by DaddyWesker** [comment]
With 1.19.4 and this PR test_observation.py now fails

```
FAIL: test_observation_from_ray (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 41, in test_observation_from_ray
    self.assertGreater(dist, 10)
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/base_test.py", line 55, in assertGreater
    super().assertGreater(a, b, msg)
AssertionError: 6.612410774134846 not greater than 10
```

**Comment by DaddyWesker** [comment]
Also, in test_vereya get_img returns None since mc.waitNotNoneObserve('getImageFrame') gives None. 
 
It is also using 1.19.4 and this PR

**Comment by DaddyWesker** [comment]
Lumberjack3D not working. Agent just stands. 

Also visualizer not working at all (i'm using your PR's visualizer and 1.19.4 vereya)

**Comment by DaddyWesker** [comment]
Test observation still fails but now with this
```
======================================================================
FAIL: test_observation_from_ray (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 41, in test_observation_from_ray
    self.assertGreater(dist, 10)
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/base_test.py", line 55, in assertGreater
    super().assertGreater(a, b, msg)
AssertionError: 2.527812539572769 not greater than 10

----------------------------------------------------------------------
Ran 5 tests in 13.158s

FAILED (failures=1)

Process finished with exit code 1

```

This test fails only when restarting it without reloading the world.

In test_vereya img is still None here` img_frame = mc.waitNotNoneObserve('getImageFrame')`


In agent.py self.rob.getCachedObserve('getNeuralSegmentation') returns None too. 

In lumberjack3d this line self.rob.updateAllObservations() just hangs for ever. Nothing happens. It seems, this line `while not all([self.cached[method][0] is not None or method in self.canBeNone for method in self.methods]):` is always True so this loop is not breaking. It happens since these two methods `getImageFrame, getNeuralSegmentation` give None and they are not in canBeNone list.

**Comment by DaddyWesker** [comment]
Screenshot from 2023-05-25 07-10-16

For some reason test_vereya now gives me this image. Instead of this:
Screenshot from 2023-05-25 07-10-45

**Review by DaddyWesker — APPROVED** [review]

**Comment by DaddyWesker** [comment]
Everything works fine now

**Pull request merged**
