### PR TITLE
use lock file to avoid concurrent runs

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Comment by noskill** [comment]
@DaddyWesker there is an error during tests RobustObserver.getBlockFromBigGrid() takes 1 positional argument but 2 were given

**Comment by DaddyWesker** [comment]
@noskill  so, in this PR or in mine? I've got two comments from you in different PRs.

**Comment by noskill** [comment]
I think issue was introduced in pr https://github.com/trueagi-io/minecraft-demo/pull/158

**Comment by noskill** [comment]
The test fails in all pull requests

**Review by DaddyWesker — APPROVED** [review]

**Pull request merged**
