### PR TITLE
malmo renamed to vereya

### PR DESCRIPTION
**Pull request by Necr0x0Der**

### CODE REVIEW

**Comment by DaddyWesker** [comment]
In experiments/test_horizon.py 
`from examples.neural import get_image`
should be changed to 
`from examples.vision.neural import get_image`
as i understand.

Also, in the same file line
`import tagilmo.utils.mission_builder as mb`
is duplicated. This comes from main of the minecraft-demo repo (i've changed it there today though).

Same (both comments) goes to test_water.py.

**Comment by Necr0x0Der** [comment]
> from examples.neural import get_image

thanks

> Also, in the same file line

I didn't fix other importing issues in `experiments` since there are too many of them, and I'd prefer the authors to spend their time on this.

**Comment by DaddyWesker** [comment]
> thanks

And test_water.py too have same issue - `from examples.neural import get_image`

> I didn't fix other importing issues in `experiments` since there are too many of them, and I'd prefer the authors to spend their time on this.

Ok, got it. 

Other than that, everything is fine from my point of view.

**Review by DaddyWesker — APPROVED** [review]

**Comment by CICS-Oleg** [comment]
I've checked and it's also fine for me.

**Pull request merged**
