### PR TITLE
get minecraft version from ping xml

### PR DESCRIPTION
**Pull request by noskill**
code for pr https://github.com/trueagi-io/Vereya/pull/33

### CODE REVIEW

**Comment by DaddyWesker** [comment]
Works for minecraft 1.18.1 and gives right game version. On 1.18.2 game i crashing. I guess this is due to the Vereya branch add_ve is currently working with 1.18.1, right?

**Comment by noskill** [comment]
I didn't test 1.18.1 only 1.18

**Review by CICS-Oleg — COMMENTED** [review]
I've tried to call getVersion from mc in test script for minecraft 1.18.1, but it gave me None.

**Comment by DaddyWesker** [comment]
> I've tried to call getVersion from mc in test script for minecraft 1.18.1, but it gave me None.

Have you built vereya's add_ve branch from Anatoly's fork? Mods generated with this fork should be placed to mods folder of minecraft.

**Comment by CICS-Oleg** [comment]
> > I've tried to call getVersion from mc in test script for minecraft 1.18.1, but it gave me None.
> 
> Have you built vereya's add_ve branch from Anatoly's fork? Mods generated with this fork should be placed to mods folder of minecraft.

Yes, I did.

**Comment by DaddyWesker** [comment]
> > > I've tried to call getVersion from mc in test script for minecraft 1.18.1, but it gave me None.
> > 
> > 
> > Have you built vereya's add_ve branch from Anatoly's fork? Mods generated with this fork should be placed to mods folder of minecraft.
> 
> Yes, I did.

can you show code which you're using to get game version? Full code.

**Comment by CICS-Oleg** [comment]
```
import logging
import json
import time
import tagilmo.utils.mission_builder as mb
from tagilmo.utils.malmo_wrapper import MalmoConnector, RobustObserver


def init_mission(mc, start_x=None, start_y=None):
    want_depth = False
    video_producer = mb.VideoProducer(width=320 * 4,
                                      height=240 * 4, want_depth=want_depth)

    obs = mb.Observations()
    obs.gridNear = [[-1, 1], [-2, 1], [-1, 1]]


    agent_handlers = mb.AgentHandlers(observations=obs, video_producer=video_producer)

    print('starting at ({0}, {1})'.format(start_x, start_y))

    miss = mb.MissionXML(
                         agentSections=[mb.AgentSection(name='Cristina',
             agenthandlers=agent_handlers,
                                      #    depth
             agentstart=mb.AgentStart([start_x, 74.0, start_y, 1]))])
    flat_json = {"biome":"minecraft:plains",
                 "layers":[{"block":"minecraft:diamond_block","height":1}],
                 "structures":{"structures": {"village":{}}}}

    flat_param = "3;7,25*1,3*3,2;1;stronghold,biome_1,village,decoration,dungeon,lake,mineshaft,lava_lake"
    flat_json = json.dumps(flat_json).replace('"', "%ESC")
    world = mb.defaultworld(
        seed='5',
        forceReuse="true",
        forceReset="false")
    flat_world = mb.flatworld(flat_json,
                    seed='43',
                    )
    miss.setWorld(world)
    miss.serverSection.initial_conditions.allowedmobs = "Pig Sheep Cow Chicken Ozelot Rabbit Villager"
    # uncomment to disable passage of time:
    miss.serverSection.initial_conditions.time_pass = 'false'
    miss.serverSection.initial_conditions.time_start = "1000"

    if mc is None:
        mc = MalmoConnector(miss)
        obs = RobustObserver(mc)
    else:
        mc.setMissionXML(miss)
    return mc, obs

def main():
    from tagilmo import VereyaPython

    start = 316.5, 5375.5
    start = (-108.0, -187.0)
    mc, obs = init_mission(None, start_x=start[0], start_y=start[1]) 

    mc.safeStart()
    time.sleep(4)
    mc.getVersion()
```

**Comment by DaddyWesker** [comment]
Weird, should work i guess. I've just put get version to the test_vereya.py main:

```
def main():
    from tagilmo import VereyaPython

    mc, obs = start_mission()
    mc.safeStart()
    mc.sendCommand('recipes')
    while True:
        cv2.waitKey(300)
        obs.clear()
        pos1, img = get_img(obs)
        if img is not None:
            img = extract(img.pixels)
            # print(mc.getNearEntities())
            if mc.observe[0] is not None and 'recipes' in mc.observe[0]:
                print("got recipes")
                mc.sendCommand('recipes off')
                version = mc.getVersion()
            cv2.imshow('img', img)
main()
```

**Comment by CICS-Oleg** [comment]
Time to rebuild all stuff. Always works :)

**Review by CICS-Oleg — APPROVED** [review]

**Pull request merged**
