### PR TITLE
stop mission when test ends

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Comment by DaddyWesker** [comment]
Hello.

I've tested this PR with your Vereya PR. Here is what I've got with test_observation.py

```
FEEEE
======================================================================
ERROR: test_observation_from_chat (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 55, in test_observation_from_chat
    self.assertEqual(command[0], "get wooden_axe")
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_observation_from_item (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 59, in test_observation_from_item
    self.assertGreater(len(item_list), 0, "item_list len")
TypeError: object of type 'NoneType' has no len()

======================================================================
ERROR: test_observation_from_ray (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 38, in test_observation_from_ray
    dist = self.getDist()
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 78, in getDist
    pitch = pos[3]
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_observation_from_triples (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 64, in test_observation_from_triples
    self.assertGreater(len(blockdrops), 0, "blockdrops len")
TypeError: object of type 'NoneType' has no len()

======================================================================
FAIL: test_game_state (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 68, in test_game_state
    self.assertTrue(self.mc.getFullStat(key="isPaused") is not None)
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/base_test.py", line 43, in assertTrue
    super().assertTrue(expr, msg)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5 tests in 36.670s

FAILED (failures=1, errors=4)

Process finished with exit code 1
```

On the second time it went normal and other consequent times it went well too. But I've got how to reproduce this behavior. It happens every first time when you launch the game. So I've closed the game and re-launched it. And then I've launched the test and it failed.  This goes only to test_observation. 

Add.

Well, this happened second time

```
...F.
======================================================================
FAIL: test_observation_from_ray (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 39, in test_observation_from_ray
    self.assertGreater(dist, 0)
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/base_test.py", line 55, in assertGreater
    super().assertGreater(a, b, msg)
AssertionError: 0 not greater than 0

----------------------------------------------------------------------
Ran 5 tests in 15.504s

FAILED (failures=1)

Process finished with exit code 1

```

**Comment by noskill** [comment]
@DaddyWesker I can't reproduce your problem, please share logs from minecraft and tests

**Comment by DaddyWesker** [comment]
@noskill 
Here is the output in terminal where I've launched minecraft https://docs.google.com/document/d/1oi950JN6sJaB-4zWQvJdVHotKbA5TJ-0LjiMQqwbEbs/edit?usp=sharing

And here is the console output in script test_observation
```
/home/daddywesker/anaconda3/envs/malmo/bin/python /home/daddywesker/pycharm/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 36547 --file /home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py 
starting at (-125.0, 73.0)
.E..{'layers': '1', 'type': 'snow', 'hitType': 'BLOCK', 'x': -137.5, 'y': 71.125, 'z': 23.16280368126394, 'distance': 3.053776098408367, 'inRange': True}
.
======================================================================
ERROR: test_observation_from_chat (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leron/noskill_fork/minecraft-demo/tests/vereya/test_observation.py", line 55, in test_observation_from_chat
    self.assertEqual(command[0], "get wooden_axe")
TypeError: 'NoneType' object is not subscriptable

----------------------------------------------------------------------
Ran 5 tests in 42.351s

FAILED (errors=1)

Process finished with exit code 1
```

**Comment by noskill** [comment]
@DaddyWesker I need full logs, terminal logs are not useful

**Review by DaddyWesker — APPROVED** [review]

**Pull request merged**
