### PR TITLE
changes related to big grid

### PR DESCRIPTION
**Pull request by DaddyWesker**
So, those changes are for new functionality - getting grid bigger than normal one. Current size of bigger grid is [-25;25] for each dimension. 

If you want to get this big grid for example in achiever.py just for test, here is the line `biggrid = agent.rob.getBigGrid()` . Currently this big grid not in use but it could be. 

To test this PR you need to use[ this PR](https://github.com/trueagi-io/Vereya/pull/55) from Vereya

### CODE REVIEW

**Comment by Necr0x0Der** [comment]
The idea was not to transmit a big grid to the client side, but to pass a block name to search in a big grid on Vereya side and send only coordinates of found blocks (limiting them to a certain number of closest blocks probably)

**Comment by DaddyWesker** [comment]
@Necr0x0Der  Done. Also I thought it could be good to write test for this functionality.

**Comment by DaddyWesker** [comment]
I've added test for observation from big grid. Seems working.

**Review by Necr0x0Der — APPROVED** [review]

**Comment by Necr0x0Der** [comment]
Works for me. I don't like `sleep(1)`, but this seems to require a more principled solution going outside this PR. Not sure if `waitNotNoneObserve` with `observeReq=True` would work better. Also, I wouldn't run `updateBlocksFromBigGrid` if the location of the necessary block is already known, but this is a minor point.

**Comment by Necr0x0Der** [comment]
And it seems that 1 second is not always enough - the agent can crash with `TypeError: 'NoneType' object is not iterable` in in `updateBlocksFromBigGrid`  `pos = int_coords(block_pos)`, when the result is not `Empty`, but `None`. So, at least it should be checked

**Comment by DaddyWesker** [comment]
> Not sure if waitNotNoneObserve with observeReq=True would work better

I've implemented this variant. We could test now if it works better

> Also, I wouldn't run updateBlocksFromBigGrid if the location of the necessary block is already known, but this is a minor point.

Done

>So, at least it should be checked

Done

**Review by Necr0x0Der — APPROVED** [review]

**Review by noskill — APPROVED** [review]

**Pull request merged**
