### PR TITLE
mine_and_craft updated

### PR DESCRIPTION
**Pull request by DaddyWesker**
Some updates to 4_mine_and_craft.py
@noskill 
@CICS-Oleg 
Guys, add yourselves to reviewers please

### CODE REVIEW

**Review by CICS-Oleg — COMMENTED** [review]
Does it work identically for both versions of mods?

**Comment by DaddyWesker** [comment]
@CICS-Oleg  By "both version" you mean which ones?

**Comment by CICS-Oleg** [comment]
I mean vereya and malmo.

**Comment by DaddyWesker** [comment]
Okay. I'll make another PR when i'll split scripts for vereya and malmo

**Pull request closed without merging**
